services:
  app:
    build:
      context: .  # Define o diretório atual como contexto
      dockerfile: Dockerfile  # Usa o Dockerfile criado acima
    ports:
      - "5001:5001"  # Mapeia a porta 5001 do container para a máquina host
    environment:
      - PYTHONUNBUFFERED=1  # Garante saída sem buffer
    volumes:
      - .:/app  # Monta o diretório atual dentro do container
    command: python run.py  # Comando para iniciar o servidor Python
