SAMPLE_RATE = 16000 # In Hz

BUFFER_DURATION = 5  # Seconds

SILENCE_THRESHOLD = 0.01

HALF_BUFFER = BUFFER_DURATION // 2
BUFFER_SIZE = SAMPLE_RATE * BUFFER_DURATION
HALF_BUFFER_SIZE = SAMPLE_RATE * HALF_BUFFER

